services:
  - type: web
    name: tienda-net-api
    runtime: dotnet
    repo: https://github.com/BeelzeDevs/Backend-TiendaNetAPI
    branch: deploy
    buildCommand: dotnet publish TiendaNetApi/TiendaNetApi.csproj -c Release -o out
    startCommand: dotnet out/TiendaNetApi.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: esta-es-una-clave-secreta-para-token
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d1e8kvngi27c73ebagbg-a.ohio-postgres.render.com;Port=5432;Database=tiendanetapi;Username=ignacio;Password=6IgmdNZSjKEGq5pouKEsEAGjdGuLhk1j;SSL Mode=Require
