services:
  - type: web
    name: tiendanetapi
    runtime: docker
    repo: https://github.com/BeelzeDevs/Backend-TiendaNetAPI
    branch: deploy
    dockerfilePath: ./Dockerfile 
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=ep-rough-voice-acpgbxuh-pooler.sa-east-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_pAtHGPs4jUx8;SSL Mode=Require;Trust Server Certificate=true"
      - key: Jwt__Key
        value: esta-es-una-clave-secreta-para-token